// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen';
import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client/index';
import type { AddFavoriteData, AddFavoriteErrors, AddFavoriteResponses, CreateNewsData, CreateNewsErrors, CreateNewsResponses, CreateRecipeData, CreateRecipeErrors, CreateRecipeResponses, CreateUserData, CreateUserErrors, CreateUserResponses, DeleteRecipeData, DeleteRecipeErrors, DeleteRecipeResponses, DeleteUserData, DeleteUserErrors, DeleteUserResponses, GetMeData, GetMeErrors, GetMeResponses, GetNewsData, GetNewsErrors, GetNewsResponses, GetRecipeAnonymousData, GetRecipeAnonymousErrors, GetRecipeAnonymousResponses, GetRecipeData, GetRecipeErrors, GetRecipeResponses, GetUserData, GetUserErrors, GetUserFavoritesData, GetUserFavoritesErrors, GetUserFavoritesResponses, GetUserRecipesAnonymousData, GetUserRecipesAnonymousErrors, GetUserRecipesAnonymousResponses, GetUserRecipesData, GetUserRecipesErrors, GetUserRecipesResponses, GetUserResponses, RemoveFavoriteData, RemoveFavoriteErrors, RemoveFavoriteResponses, SearchRecipesAnonymousData, SearchRecipesAnonymousErrors, SearchRecipesAnonymousResponses, SearchRecipesData, SearchRecipesErrors, SearchRecipesResponses, UpdateRecipeData, UpdateRecipeErrors, UpdateRecipeResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List news items
 */
export const getNews = <ThrowOnError extends boolean = false>(options?: Options<GetNewsData, ThrowOnError>): RequestResult<GetNewsResponses, GetNewsErrors, ThrowOnError> => (options?.client ?? client).get<GetNewsResponses, GetNewsErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/news',
    ...options
});

/**
 * Create a news item
 */
export const createNews = <ThrowOnError extends boolean = false>(options: Options<CreateNewsData, ThrowOnError>): RequestResult<CreateNewsResponses, CreateNewsErrors, ThrowOnError> => (options.client ?? client).post<CreateNewsResponses, CreateNewsErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/news',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Remove a recipe from favorites
 */
export const removeFavorite = <ThrowOnError extends boolean = false>(options: Options<RemoveFavoriteData, ThrowOnError>): RequestResult<RemoveFavoriteResponses, RemoveFavoriteErrors, ThrowOnError> => (options.client ?? client).delete<RemoveFavoriteResponses, RemoveFavoriteErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/recipes/{slug}/favorite',
    ...options
});

/**
 * Add a recipe to favorites
 */
export const addFavorite = <ThrowOnError extends boolean = false>(options: Options<AddFavoriteData, ThrowOnError>): RequestResult<AddFavoriteResponses, AddFavoriteErrors, ThrowOnError> => (options.client ?? client).post<AddFavoriteResponses, AddFavoriteErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/recipes/{slug}/favorite',
    ...options
});

/**
 * Search and list recipes
 */
export const searchRecipes = <ThrowOnError extends boolean = false>(options?: Options<SearchRecipesData, ThrowOnError>): RequestResult<SearchRecipesResponses, SearchRecipesErrors, ThrowOnError> => (options?.client ?? client).get<SearchRecipesResponses, SearchRecipesErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/recipes',
    ...options
});

/**
 * Create a new recipe
 */
export const createRecipe = <ThrowOnError extends boolean = false>(options: Options<CreateRecipeData, ThrowOnError>): RequestResult<CreateRecipeResponses, CreateRecipeErrors, ThrowOnError> => (options.client ?? client).post<CreateRecipeResponses, CreateRecipeErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/recipes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a recipe (soft delete)
 */
export const deleteRecipe = <ThrowOnError extends boolean = false>(options: Options<DeleteRecipeData, ThrowOnError>): RequestResult<DeleteRecipeResponses, DeleteRecipeErrors, ThrowOnError> => (options.client ?? client).delete<DeleteRecipeResponses, DeleteRecipeErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/recipes/{slug}',
    ...options
});

/**
 * Get a recipe by slug
 */
export const getRecipe = <ThrowOnError extends boolean = false>(options: Options<GetRecipeData, ThrowOnError>): RequestResult<GetRecipeResponses, GetRecipeErrors, ThrowOnError> => (options.client ?? client).get<GetRecipeResponses, GetRecipeErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/recipes/{slug}',
    ...options
});

/**
 * Update a recipe
 */
export const updateRecipe = <ThrowOnError extends boolean = false>(options: Options<UpdateRecipeData, ThrowOnError>): RequestResult<UpdateRecipeResponses, UpdateRecipeErrors, ThrowOnError> => (options.client ?? client).put<UpdateRecipeResponses, UpdateRecipeErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/recipes/{slug}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Search and list recipes (no auth)
 */
export const searchRecipesAnonymous = <ThrowOnError extends boolean = false>(options?: Options<SearchRecipesAnonymousData, ThrowOnError>): RequestResult<SearchRecipesAnonymousResponses, SearchRecipesAnonymousErrors, ThrowOnError> => (options?.client ?? client).get<SearchRecipesAnonymousResponses, SearchRecipesAnonymousErrors, ThrowOnError>({ url: '/anonymous/recipes', ...options });

/**
 * Get a recipe by slug (no auth)
 */
export const getRecipeAnonymous = <ThrowOnError extends boolean = false>(options: Options<GetRecipeAnonymousData, ThrowOnError>): RequestResult<GetRecipeAnonymousResponses, GetRecipeAnonymousErrors, ThrowOnError> => (options.client ?? client).get<GetRecipeAnonymousResponses, GetRecipeAnonymousErrors, ThrowOnError>({ url: '/anonymous/recipes/{slug}', ...options });

/**
 * Create a new user from the authenticated JWT
 */
export const createUser = <ThrowOnError extends boolean = false>(options?: Options<CreateUserData, ThrowOnError>): RequestResult<CreateUserResponses, CreateUserErrors, ThrowOnError> => (options?.client ?? client).post<CreateUserResponses, CreateUserErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users',
    ...options
});

/**
 * Delete a user and all their data
 */
export const deleteUser = <ThrowOnError extends boolean = false>(options: Options<DeleteUserData, ThrowOnError>): RequestResult<DeleteUserResponses, DeleteUserErrors, ThrowOnError> => (options.client ?? client).delete<DeleteUserResponses, DeleteUserErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/users/{id}',
    ...options
});

/**
 * Get a user by ID
 */
export const getUser = <ThrowOnError extends boolean = false>(options: Options<GetUserData, ThrowOnError>): RequestResult<GetUserResponses, GetUserErrors, ThrowOnError> => (options.client ?? client).get<GetUserResponses, GetUserErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/users/{id}',
    ...options
});

/**
 * Get a user's favorited recipes
 */
export const getUserFavorites = <ThrowOnError extends boolean = false>(options: Options<GetUserFavoritesData, ThrowOnError>): RequestResult<GetUserFavoritesResponses, GetUserFavoritesErrors, ThrowOnError> => (options.client ?? client).get<GetUserFavoritesResponses, GetUserFavoritesErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/users/{id}/favorites',
    ...options
});

/**
 * Get current user profile
 */
export const getMe = <ThrowOnError extends boolean = false>(options?: Options<GetMeData, ThrowOnError>): RequestResult<GetMeResponses, GetMeErrors, ThrowOnError> => (options?.client ?? client).get<GetMeResponses, GetMeErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/users/me',
    ...options
});

/**
 * Get recipes by a user
 */
export const getUserRecipes = <ThrowOnError extends boolean = false>(options: Options<GetUserRecipesData, ThrowOnError>): RequestResult<GetUserRecipesResponses, GetUserRecipesErrors, ThrowOnError> => (options.client ?? client).get<GetUserRecipesResponses, GetUserRecipesErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'access_token',
            type: 'apiKey'
        }],
    url: '/users/{id}/recipes',
    ...options
});

/**
 * Get recipes by an author (no auth)
 */
export const getUserRecipesAnonymous = <ThrowOnError extends boolean = false>(options: Options<GetUserRecipesAnonymousData, ThrowOnError>): RequestResult<GetUserRecipesAnonymousResponses, GetUserRecipesAnonymousErrors, ThrowOnError> => (options.client ?? client).get<GetUserRecipesAnonymousResponses, GetUserRecipesAnonymousErrors, ThrowOnError>({ url: '/anonymous/users/{authorId}/recipes', ...options });
