// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8001' | (string & {});
};

export type Error = {
    message: string;
    code?: string;
};

export type UserEntity = {
    id: string;
    username: string;
    createdAt: number;
};

export type UserProfile = {
    id: string;
    username: string;
    createdAt: number;
    recipeCount: number;
    favoriteCount: number;
};

export type UserCreateInput = {
    id: string;
    username?: string;
};

export type RecipeEntity = {
    id: number;
    slug: string;
    title: string;
    description?: string | null;
    ingredients?: string | null;
    recipe: string;
    authorId: string;
    createdAt: number;
    updatedAt: number;
};

export type RecipeOutput = RecipeEntity & {
    isFavorite: boolean;
};

export type RecipeWithAuthor = RecipeOutput & {
    authorUsername: string;
};

export type RecipeWithAuthorAnon = RecipeEntity & {
    authorUsername: string;
};

export type RecipesCursorResponse = {
    recipes: Array<RecipeOutput>;
    hasMore: boolean;
    nextCursor: number | null;
};

export type RecipesPageResponse = {
    recipes: Array<RecipeOutput>;
    pagination: PaginationInfo;
};

export type RecipesCursorResponseAnon = {
    recipes: Array<RecipeEntity>;
    hasMore: boolean;
    nextCursor: number | null;
};

export type RecipesPageResponseAnon = {
    recipes: Array<RecipeEntity>;
    pagination: PaginationInfo;
};

export type PaginationInfo = {
    currentPage: number;
    pageSize: number;
    totalPages: number;
    totalItems: number;
    hasNextPage: boolean;
    hasPreviousPage: boolean;
};

export type RecipeFavoriteEntity = {
    id: number;
    username: string;
    recipeId: number;
    userId: string;
    createdAt: number;
};

export type FavoritesResponse = {
    recipes: Array<RecipeOutput>;
    hasMore: boolean;
    nextCursor: number | null;
};

export type UserRecipesResponse = {
    recipes: Array<RecipeOutput>;
    hasMore: boolean;
    nextCursor: number | null;
};

export type UserRecipesResponseAnon = {
    recipes: Array<RecipeEntity>;
    hasMore: boolean;
    nextCursor: number | null;
};

export type NewsEntity = {
    id: number;
    title: string;
    text: string;
    type: string;
    authorId: string;
    recipeSlug?: string | null;
    createdAt: string;
};

export type NewsListResponse = {
    news: Array<NewsEntity>;
    hasMore: boolean;
    nextCursor: string | null;
};

export type CreateRecipeBody = {
    title: string;
    description?: string;
    ingredients?: string;
    recipe: string;
};

export type UpdateRecipeBody = {
    title: string;
    description?: string;
    ingredients?: string;
    recipe: string;
};

export type CreateNewsBody = {
    title: string;
    text: string;
    type: string;
    recipeSlug?: string | null;
};

/**
 * User ID
 */
export type UserId = string;

/**
 * Recipe slug
 */
export type Slug = string;

/**
 * Author user ID
 */
export type AuthorId = string;

/**
 * Search term for filtering by title or description
 */
export type Q = string;

/**
 * Cursor for cursor-based pagination
 */
export type Cursor = string | null;

/**
 * Page number for page-based pagination (cannot use with cursor)
 */
export type Page = number;

/**
 * Number of items per page
 */
export type PageSize = number;

export type GetNewsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Cursor for cursor-based pagination
         */
        cursor?: string | null;
        /**
         * Number of items per page
         */
        pageSize?: number;
    };
    url: '/news';
};

export type GetNewsErrors = {
    /**
     * Missing or invalid authentication
     */
    401: Error;
};

export type GetNewsError = GetNewsErrors[keyof GetNewsErrors];

export type GetNewsResponses = {
    /**
     * Paginated news list
     */
    200: NewsListResponse;
};

export type GetNewsResponse = GetNewsResponses[keyof GetNewsResponses];

export type CreateNewsData = {
    body: CreateNewsBody;
    path?: never;
    query?: never;
    url: '/news';
};

export type CreateNewsErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Missing or invalid authentication
     */
    401: Error;
};

export type CreateNewsError = CreateNewsErrors[keyof CreateNewsErrors];

export type CreateNewsResponses = {
    /**
     * News item created
     */
    201: NewsEntity;
};

export type CreateNewsResponse = CreateNewsResponses[keyof CreateNewsResponses];

export type RemoveFavoriteData = {
    body?: never;
    path: {
        /**
         * Recipe slug
         */
        slug: string;
    };
    query?: never;
    url: '/recipes/{slug}/favorite';
};

export type RemoveFavoriteErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Missing or invalid authentication
     */
    401: Error;
};

export type RemoveFavoriteError = RemoveFavoriteErrors[keyof RemoveFavoriteErrors];

export type RemoveFavoriteResponses = {
    /**
     * Favorite removed
     */
    204: void;
};

export type RemoveFavoriteResponse = RemoveFavoriteResponses[keyof RemoveFavoriteResponses];

export type AddFavoriteData = {
    body?: never;
    path: {
        /**
         * Recipe slug
         */
        slug: string;
    };
    query?: never;
    url: '/recipes/{slug}/favorite';
};

export type AddFavoriteErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Missing or invalid authentication
     */
    401: Error;
};

export type AddFavoriteError = AddFavoriteErrors[keyof AddFavoriteErrors];

export type AddFavoriteResponses = {
    /**
     * Favorite added
     */
    200: RecipeFavoriteEntity;
};

export type AddFavoriteResponse = AddFavoriteResponses[keyof AddFavoriteResponses];

export type SearchRecipesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search term for filtering by title or description
         */
        q?: string;
        /**
         * Cursor for cursor-based pagination
         */
        cursor?: string | null;
        /**
         * Page number for page-based pagination (cannot use with cursor)
         */
        page?: number;
        /**
         * Number of items per page
         */
        pageSize?: number;
    };
    url: '/recipes';
};

export type SearchRecipesErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Missing or invalid authentication
     */
    401: Error;
};

export type SearchRecipesError = SearchRecipesErrors[keyof SearchRecipesErrors];

export type SearchRecipesResponses = {
    /**
     * Paginated recipe list (cursor or page-based)
     */
    200: RecipesCursorResponse | RecipesPageResponse;
};

export type SearchRecipesResponse = SearchRecipesResponses[keyof SearchRecipesResponses];

export type CreateRecipeData = {
    body: CreateRecipeBody;
    path?: never;
    query?: never;
    url: '/recipes';
};

export type CreateRecipeErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Missing or invalid authentication
     */
    401: Error;
};

export type CreateRecipeError = CreateRecipeErrors[keyof CreateRecipeErrors];

export type CreateRecipeResponses = {
    /**
     * Recipe created
     */
    201: RecipeEntity;
};

export type CreateRecipeResponse = CreateRecipeResponses[keyof CreateRecipeResponses];

export type DeleteRecipeData = {
    body?: never;
    path: {
        /**
         * Recipe slug
         */
        slug: string;
    };
    query?: never;
    url: '/recipes/{slug}';
};

export type DeleteRecipeErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Missing or invalid authentication
     */
    401: Error;
    /**
     * Not authorized to perform this action
     */
    403: Error;
};

export type DeleteRecipeError = DeleteRecipeErrors[keyof DeleteRecipeErrors];

export type DeleteRecipeResponses = {
    /**
     * Recipe soft-deleted
     */
    204: void;
};

export type DeleteRecipeResponse = DeleteRecipeResponses[keyof DeleteRecipeResponses];

export type GetRecipeData = {
    body?: never;
    path: {
        /**
         * Recipe slug
         */
        slug: string;
    };
    query?: never;
    url: '/recipes/{slug}';
};

export type GetRecipeErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Missing or invalid authentication
     */
    401: Error;
};

export type GetRecipeError = GetRecipeErrors[keyof GetRecipeErrors];

export type GetRecipeResponses = {
    /**
     * Recipe with author info and favorite status
     */
    200: RecipeWithAuthor;
};

export type GetRecipeResponse = GetRecipeResponses[keyof GetRecipeResponses];

export type UpdateRecipeData = {
    body: UpdateRecipeBody;
    path: {
        /**
         * Recipe slug
         */
        slug: string;
    };
    query?: never;
    url: '/recipes/{slug}';
};

export type UpdateRecipeErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Missing or invalid authentication
     */
    401: Error;
    /**
     * Not authorized to perform this action
     */
    403: Error;
};

export type UpdateRecipeError = UpdateRecipeErrors[keyof UpdateRecipeErrors];

export type UpdateRecipeResponses = {
    /**
     * Recipe updated
     */
    200: RecipeEntity;
};

export type UpdateRecipeResponse = UpdateRecipeResponses[keyof UpdateRecipeResponses];

export type SearchRecipesAnonymousData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search term for filtering by title or description
         */
        q?: string;
        /**
         * Cursor for cursor-based pagination
         */
        cursor?: string | null;
        /**
         * Page number for page-based pagination (cannot use with cursor)
         */
        page?: number;
        /**
         * Number of items per page
         */
        pageSize?: number;
    };
    url: '/anonymous/recipes';
};

export type SearchRecipesAnonymousErrors = {
    /**
     * Bad request
     */
    400: Error;
};

export type SearchRecipesAnonymousError = SearchRecipesAnonymousErrors[keyof SearchRecipesAnonymousErrors];

export type SearchRecipesAnonymousResponses = {
    /**
     * Paginated recipe list (cursor or page-based)
     */
    200: RecipesCursorResponseAnon | RecipesPageResponseAnon;
};

export type SearchRecipesAnonymousResponse = SearchRecipesAnonymousResponses[keyof SearchRecipesAnonymousResponses];

export type GetRecipeAnonymousData = {
    body?: never;
    path: {
        /**
         * Recipe slug
         */
        slug: string;
    };
    query?: never;
    url: '/anonymous/recipes/{slug}';
};

export type GetRecipeAnonymousErrors = {
    /**
     * Bad request
     */
    400: Error;
};

export type GetRecipeAnonymousError = GetRecipeAnonymousErrors[keyof GetRecipeAnonymousErrors];

export type GetRecipeAnonymousResponses = {
    /**
     * Recipe with author username
     */
    200: RecipeWithAuthorAnon;
};

export type GetRecipeAnonymousResponse = GetRecipeAnonymousResponses[keyof GetRecipeAnonymousResponses];

export type CreateUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type CreateUserErrors = {
    /**
     * Missing or invalid authentication
     */
    401: Error;
    /**
     * User ID already exists
     */
    409: Error;
    /**
     * Failed to generate unique username
     */
    500: Error;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    /**
     * User created
     */
    200: UserEntity;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type DeleteUserData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type DeleteUserErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Missing or invalid authentication
     */
    401: Error;
    /**
     * Not authorized to perform this action
     */
    403: Error;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
    /**
     * User and all associated data deleted
     */
    204: void;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type GetUserData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type GetUserErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Missing or invalid authentication
     */
    401: Error;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * User profile
     */
    200: UserProfile & {
        isCurrentUser: boolean;
    };
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type GetUserFavoritesData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: {
        /**
         * Cursor for cursor-based pagination
         */
        cursor?: string | null;
        /**
         * Number of items per page
         */
        pageSize?: number;
    };
    url: '/users/{id}/favorites';
};

export type GetUserFavoritesErrors = {
    /**
     * Missing or invalid authentication
     */
    401: Error;
};

export type GetUserFavoritesError = GetUserFavoritesErrors[keyof GetUserFavoritesErrors];

export type GetUserFavoritesResponses = {
    /**
     * Paginated list of favorited recipes
     */
    200: FavoritesResponse;
};

export type GetUserFavoritesResponse = GetUserFavoritesResponses[keyof GetUserFavoritesResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetMeErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Missing or invalid authentication
     */
    401: Error;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * Current user profile with recipe and favorite counts
     */
    200: UserProfile;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type UpdateUserData = {
    body: unknown;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UpdateUserErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Missing or invalid authentication
     */
    401: Error;
    409: unknown;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    /**
     * User updated
     */
    200: UserEntity;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type GetUserRecipesData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: {
        /**
         * Cursor for cursor-based pagination
         */
        cursor?: string | null;
        /**
         * Number of items per page
         */
        pageSize?: number;
    };
    url: '/users/{id}/recipes';
};

export type GetUserRecipesErrors = {
    /**
     * Missing or invalid authentication
     */
    401: Error;
};

export type GetUserRecipesError = GetUserRecipesErrors[keyof GetUserRecipesErrors];

export type GetUserRecipesResponses = {
    /**
     * Paginated list of recipes
     */
    200: UserRecipesResponse;
};

export type GetUserRecipesResponse = GetUserRecipesResponses[keyof GetUserRecipesResponses];

export type GetUserRecipesAnonymousData = {
    body?: never;
    path: {
        /**
         * Author user ID
         */
        authorId: string;
    };
    query?: {
        /**
         * Cursor for cursor-based pagination
         */
        cursor?: string | null;
        /**
         * Number of items per page
         */
        pageSize?: number;
    };
    url: '/anonymous/users/{authorId}/recipes';
};

export type GetUserRecipesAnonymousErrors = {
    /**
     * Bad request
     */
    400: Error;
};

export type GetUserRecipesAnonymousError = GetUserRecipesAnonymousErrors[keyof GetUserRecipesAnonymousErrors];

export type GetUserRecipesAnonymousResponses = {
    /**
     * Paginated list of recipes
     */
    200: UserRecipesResponseAnon;
};

export type GetUserRecipesAnonymousResponse = GetUserRecipesAnonymousResponses[keyof GetUserRecipesAnonymousResponses];
